const ACTIONS = {
  DISPLAY_ALERT: 'SHOW_ALERT',
  CLEAR_ALERT: 'CLEAR_ALERT',
  DISPLAY_SUCCESS: 'DISPLAY_SUCCESS',
  PW_MATCH: 'PW_MATCH',
  AUTH_BEGIN: 'AUTH_BEGIN',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  RESET: 'RESET',
  LOGOUT: 'LOGOUT',
  SET_PAGE: 'SET_PAGE',
  MODAL_MENU_TOGGLE: 'MODAL_MENU_TOGGLE',
};

export default ACTIONS;
