const ACTIONS = {
  DISPLAY_ALERT: 'SHOW_ALERT',
  CLEAR_ALERT: 'CLEAR_ALERT',
  DISPLAY_SUCCESS: 'DISPLAY_SUCCESS',
  PW_MATCH: 'PW_MATCH',
  REGISTER_BEGIN: 'REGISTER_BEGIN',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',
};

export default ACTIONS;
