const avatarOptions = [
  {
    id: 1,
    value: 'top',
    optionType: 'Top',
    options: [
      'NoHair',
      'Hat',
      'Turban',
      'WinterHat1',
      'WinterHat3',
      'WinterHat4',
      'LongHairBigHair',
      'LongHairBob',
      'LongHairBun',
      'LongHairCurly',
      'LongHairCurvy',
      'LongHairDreads',
      'LongHairFrida',
      'LongHairFro',
      'LongHairFroBand',
      'LongHairNotTooLong',
      'LongHairShavedSides',
      'LongHairMiaWallace',
      'LongHairStraight',
      'LongHairStraight2',
      'LongHairStraightStrand',
      'ShortHairDreads01',
      'ShortHairDreads02',
      'ShortHairFrizzle',
      'ShortHairShaggyMullet',
      'ShortHairShortCurly',
      'ShortHairShortFlat',
      'ShortHairShortRound',
      'ShortHairShortWaved',
      'ShortHairSides',
      'ShortHairTheCaesar',
    ],
  },
  {
    id: 2,
    value: 'accessories',
    optionType: 'Accessories',
    options: [
      'Blank',
      'Round',
      'Sunglasses',
      'Kurt',
      'Wayfarers',
      'Prescription01',
      'Prescription02',
    ],
  },
  {
    id: 3,
    value: 'hairColor',
    optionType: 'Hair Color',
    options: [
      'Brown',
      'BrownDark',
      'Auburn',
      'Black',
      'Blonde',
      'BlondeGolden',
      'SilverGray',
      'Red',
      'Platinum',
    ],
  },
  {
    id: 4,
    value: 'facialHair',
    optionType: 'Facial Hair',
    options: [
      'Blank',
      'BeardMedium',
      'BeardLight',
      'BeardMajestic',
      'MoustacheFancy',
      'MoustacheMagnum',
    ],
  },
  {
    id: 5,
    value: 'facialHairColor',
    optionType: 'Facial Hair Color',
    options: ['BrownDark', 'Auburn', 'Black', 'Blonde', 'BlondeGolden'],
  },
  {
    id: 6,
    value: 'clothes',
    optionType: 'Clothes',
    options: [
      'Hoodie',
      'ShirtCrewNeck',
      'GraphicShirt',
      'BlazerSweater',
      'ShirtScoopNeck',
    ],
  },
  {
    id: 7,
    value: 'fabricColor',
    optionType: 'Fabric Color',
    options: [
      'Black',
      'Blue01',
      'Blue02',
      'Blue03',
      'Gray01',
      'Gray02',
      'Heather',
      'PastelBlue',
      'PastelGreen',
      'PastelOrange',
      'PastelYellow',
      'Pink',
      'Red',
      'White',
    ],
  },
  {
    id: 8,
    value: 'eyes',
    optionType: 'Eyes',
    options: [
      'Close',
      'Cry',
      'Default',
      'Dizzy',
      'EyeRoll',
      'Happy',
      'Side',
      'Squint',
      'Surprised',
      'Wink',
      'WinkWacky',
    ],
  },
  {
    id: 9,
    value: 'eyebrows',
    optionType: 'Eyebrows',
    options: [
      'Angry',
      'AngryNatural',
      'Default',
      'DefaultNatural',
      'FlatNatural',
      'RaisedExcited',
      'SadConcerned',
      'UnibrowNatural',
      'UpDown',
      'UpDownNatural',
    ],
  },
  {
    id: 10,
    value: 'mouth',
    optionType: 'Mouth',
    options: [
      'Concerned',
      'Default',
      'Disbelief',
      'Eating',
      'Grimace',
      'Sad',
      'ScreamOpen',
      'Serious',
      'Smile',
      'Tongue',
      'Twinkle',
      'Vomit',
    ],
  },
  {
    id: 11,
    value: 'skin',
    optionType: 'Skin',
    options: [
      'Tanned',
      'Yellow',
      'Pale',
      'Light',
      'Brown',
      'DarkBrown',
      'Black',
    ],
  },
];

export default avatarOptions;
